<?php
return [
    ['alpha_2_code' => 'AD', 'name' => 'ANDORRA', 'code' => '376'],
    ['alpha_2_code' => 'AE', 'name' => 'UNITED ARAB EMIRATES', 'code' => '971'],
    ['alpha_2_code' => 'AF', 'name' => 'AFGHANISTAN', 'code' => '93'],
    ['alpha_2_code' => 'AG', 'name' => 'ANTIGUA AND BARBUDA', 'code' => '1268'],
    ['alpha_2_code' => 'AI', 'name' => 'ANGUILLA', 'code' => '1264'],
    ['alpha_2_code' => 'AL', 'name' => 'ALBANIA', 'code' => '355'],
    ['alpha_2_code' => 'AM', 'name' => 'ARMENIA', 'code' => '374'],
    ['alpha_2_code' => 'AN', 'name' => 'NETHERLANDS ANTILLES', 'code' => '599'],
    ['alpha_2_code' => 'AO', 'name' => 'ANGOLA', 'code' => '244'],
    ['alpha_2_code' => 'AQ', 'name' => 'ANTARCTICA', 'code' => '672'],
    ['alpha_2_code' => 'AR', 'name' => 'ARGENTINA', 'code' => '54'],
    ['alpha_2_code' => 'AS', 'name' => 'AMERICAN SAMOA', 'code' => '1684'],
    ['alpha_2_code' => 'AT', 'name' => 'AUSTRIA', 'code' => '43'],
    ['alpha_2_code' => 'AU', 'name' => 'AUSTRALIA', 'code' => '61'],
    ['alpha_2_code' => 'AW', 'name' => 'ARUBA', 'code' => '297'],
    ['alpha_2_code' => 'AZ', 'name' => 'AZERBAIJAN', 'code' => '994'],
    ['alpha_2_code' => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA', 'code' => '387'],
    ['alpha_2_code' => 'BB', 'name' => 'BARBADOS', 'code' => '1246'],
    ['alpha_2_code' => 'BD', 'name' => 'BANGLADESH', 'code' => '880'],
    ['alpha_2_code' => 'BE', 'name' => 'BELGIUM', 'code' => '32'],
    ['alpha_2_code' => 'BF', 'name' => 'BURKINA FASO', 'code' => '226'],
    ['alpha_2_code' => 'BG', 'name' => 'BULGARIA', 'code' => '359'],
    ['alpha_2_code' => 'BH', 'name' => 'BAHRAIN', 'code' => '973'],
    ['alpha_2_code' => 'BI', 'name' => 'BURUNDI', 'code' => '257'],
    ['alpha_2_code' => 'BJ', 'name' => 'BENIN', 'code' => '229'],
    ['alpha_2_code' => 'BL', 'name' => 'SAINT BARTHELEMY', 'code' => '590'],
    ['alpha_2_code' => 'BM', 'name' => 'BERMUDA', 'code' => '1441'],
    ['alpha_2_code' => 'BN', 'name' => 'BRUNEI DARUSSALAM', 'code' => '673'],
    ['alpha_2_code' => 'BO', 'name' => 'BOLIVIA', 'code' => '591'],
    ['alpha_2_code' => 'BR', 'name' => 'BRAZIL', 'code' => '55'],
    ['alpha_2_code' => 'BS', 'name' => 'BAHAMAS', 'code' => '1242'],
    ['alpha_2_code' => 'BT', 'name' => 'BHUTAN', 'code' => '975'],
    ['alpha_2_code' => 'BW', 'name' => 'BOTSWANA', 'code' => '267'],
    ['alpha_2_code' => 'BY', 'name' => 'BELARUS', 'code' => '375'],
    ['alpha_2_code' => 'BZ', 'name' => 'BELIZE', 'code' => '501'],
    ['alpha_2_code' => 'CA', 'name' => 'CANADA', 'code' => '1'],
    ['alpha_2_code' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS', 'code' => '61'],
    ['alpha_2_code' => 'CD', 'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'code' => '243'],
    ['alpha_2_code' => 'CF', 'name' => 'CENTRAL AFRICAN REPUBLIC', 'code' => '236'],
    ['alpha_2_code' => 'CG', 'name' => 'CONGO', 'code' => '242'],
    ['alpha_2_code' => 'CH', 'name' => 'SWITZERLAND', 'code' => '41'],
    ['alpha_2_code' => 'CI', 'name' => 'COTE D IVOIRE', 'code' => '225'],
    ['alpha_2_code' => 'CK', 'name' => 'COOK ISLANDS', 'code' => '682'],
    ['alpha_2_code' => 'CL', 'name' => 'CHILE', 'code' => '56'],
    ['alpha_2_code' => 'CM', 'name' => 'CAMEROON', 'code' => '237'],
    ['alpha_2_code' => 'CN', 'name' => 'CHINA', 'code' => '86'],
    ['alpha_2_code' => 'CO', 'name' => 'COLOMBIA', 'code' => '57'],
    ['alpha_2_code' => 'CR', 'name' => 'COSTA RICA', 'code' => '506'],
    ['alpha_2_code' => 'CU', 'name' => 'CUBA', 'code' => '53'],
    ['alpha_2_code' => 'CV', 'name' => 'CAPE VERDE', 'code' => '238'],
    ['alpha_2_code' => 'CX', 'name' => 'CHRISTMAS ISLAND', 'code' => '61'],
    ['alpha_2_code' => 'CY', 'name' => 'CYPRUS', 'code' => '357'],
    ['alpha_2_code' => 'CZ', 'name' => 'CZECH REPUBLIC', 'code' => '420'],
    ['alpha_2_code' => 'DE', 'name' => 'GERMANY', 'code' => '49'],
    ['alpha_2_code' => 'DJ', 'name' => 'DJIBOUTI', 'code' => '253'],
    ['alpha_2_code' => 'DK', 'name' => 'DENMARK', 'code' => '45'],
    ['alpha_2_code' => 'DM', 'name' => 'DOMINICA', 'code' => '1767'],
    ['alpha_2_code' => 'DO', 'name' => 'DOMINICAN REPUBLIC', 'code' => '1809'],
    ['alpha_2_code' => 'DZ', 'name' => 'ALGERIA', 'code' => '213'],
    ['alpha_2_code' => 'EC', 'name' => 'ECUADOR', 'code' => '593'],
    ['alpha_2_code' => 'EE', 'name' => 'ESTONIA', 'code' => '372'],
    ['alpha_2_code' => 'EG', 'name' => 'EGYPT', 'code' => '20'],
    ['alpha_2_code' => 'ER', 'name' => 'ERITREA', 'code' => '291'],
    ['alpha_2_code' => 'ES', 'name' => 'SPAIN', 'code' => '34'],
    ['alpha_2_code' => 'ET', 'name' => 'ETHIOPIA', 'code' => '251'],
    ['alpha_2_code' => 'FI', 'name' => 'FINLAND', 'code' => '358'],
    ['alpha_2_code' => 'FJ', 'name' => 'FIJI', 'code' => '679'],
    ['alpha_2_code' => 'FK', 'name' => 'FALKLAND ISLANDS (MALVINAS)', 'code' => '500'],
    ['alpha_2_code' => 'FM', 'name' => 'MICRONESIA, FEDERATED STATES OF', 'code' => '691'],
    ['alpha_2_code' => 'FO', 'name' => 'FAROE ISLANDS', 'code' => '298'],
    ['alpha_2_code' => 'FR', 'name' => 'FRANCE', 'code' => '33'],
    ['alpha_2_code' => 'GA', 'name' => 'GABON', 'code' => '241'],
    ['alpha_2_code' => 'GB', 'name' => 'UNITED KINGDOM', 'code' => '44'],
    ['alpha_2_code' => 'GD', 'name' => 'GRENADA', 'code' => '1473'],
    ['alpha_2_code' => 'GE', 'name' => 'GEORGIA', 'code' => '995'],
    ['alpha_2_code' => 'GH', 'name' => 'GHANA', 'code' => '233'],
    ['alpha_2_code' => 'GI', 'name' => 'GIBRALTAR', 'code' => '350'],
    ['alpha_2_code' => 'GL', 'name' => 'GREENLAND', 'code' => '299'],
    ['alpha_2_code' => 'GM', 'name' => 'GAMBIA', 'code' => '220'],
    ['alpha_2_code' => 'GN', 'name' => 'GUINEA', 'code' => '224'],
    ['alpha_2_code' => 'GQ', 'name' => 'EQUATORIAL GUINEA', 'code' => '240'],
    ['alpha_2_code' => 'GR', 'name' => 'GREECE', 'code' => '30'],
    ['alpha_2_code' => 'GT', 'name' => 'GUATEMALA', 'code' => '502'],
    ['alpha_2_code' => 'GU', 'name' => 'GUAM', 'code' => '1671'],
    ['alpha_2_code' => 'GW', 'name' => 'GUINEA-BISSAU', 'code' => '245'],
    ['alpha_2_code' => 'GY', 'name' => 'GUYANA', 'code' => '592'],
    ['alpha_2_code' => 'HK', 'name' => 'HONG KONG', 'code' => '852'],
    ['alpha_2_code' => 'HN', 'name' => 'HONDURAS', 'code' => '504'],
    ['alpha_2_code' => 'HR', 'name' => 'CROATIA', 'code' => '385'],
    ['alpha_2_code' => 'HT', 'name' => 'HAITI', 'code' => '509'],
    ['alpha_2_code' => 'HU', 'name' => 'HUNGARY', 'code' => '36'],
    ['alpha_2_code' => 'ID', 'name' => 'INDONESIA', 'code' => '62'],
    ['alpha_2_code' => 'IE', 'name' => 'IRELAND', 'code' => '353'],
    ['alpha_2_code' => 'IL', 'name' => 'ISRAEL', 'code' => '972'],
    ['alpha_2_code' => 'IM', 'name' => 'ISLE OF MAN', 'code' => '44'],
    ['alpha_2_code' => 'IN', 'name' => 'INDIA', 'code' => '91'],
    ['alpha_2_code' => 'IQ', 'name' => 'IRAQ', 'code' => '964'],
    ['alpha_2_code' => 'IR', 'name' => 'IRAN, ISLAMIC REPUBLIC OF', 'code' => '98'],
    ['alpha_2_code' => 'IS', 'name' => 'ICELAND', 'code' => '354'],
    ['alpha_2_code' => 'IT', 'name' => 'ITALY', 'code' => '39'],
    ['alpha_2_code' => 'JM', 'name' => 'JAMAICA', 'code' => '1876'],
    ['alpha_2_code' => 'JO', 'name' => 'JORDAN', 'code' => '962'],
    ['alpha_2_code' => 'JP', 'name' => 'JAPAN', 'code' => '81'],
    ['alpha_2_code' => 'KE', 'name' => 'KENYA', 'code' => '254'],
    ['alpha_2_code' => 'KG', 'name' => 'KYRGYZSTAN', 'code' => '996'],
    ['alpha_2_code' => 'KH', 'name' => 'CAMBODIA', 'code' => '855'],
    ['alpha_2_code' => 'KI', 'name' => 'KIRIBATI', 'code' => '686'],
    ['alpha_2_code' => 'KM', 'name' => 'COMOROS', 'code' => '269'],
    ['alpha_2_code' => 'KN', 'name' => 'SAINT KITTS AND NEVIS', 'code' => '1869'],
    ['alpha_2_code' => 'KP', 'name' => 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', 'code' => '850'],
    ['alpha_2_code' => 'KR', 'name' => 'KOREA REPUBLIC OF', 'code' => '82'],
    ['alpha_2_code' => 'KW', 'name' => 'KUWAIT', 'code' => '965'],
    ['alpha_2_code' => 'KY', 'name' => 'CAYMAN ISLANDS', 'code' => '1345'],
    ['alpha_2_code' => 'KZ', 'name' => 'KAZAKSTAN', 'code' => '7'],
    ['alpha_2_code' => 'LA', 'name' => 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'code' => '856'],
    ['alpha_2_code' => 'LB', 'name' => 'LEBANON', 'code' => '961'],
    ['alpha_2_code' => 'LC', 'name' => 'SAINT LUCIA', 'code' => '1758'],
    ['alpha_2_code' => 'LI', 'name' => 'LIECHTENSTEIN', 'code' => '423'],
    ['alpha_2_code' => 'LK', 'name' => 'SRI LANKA', 'code' => '94'],
    ['alpha_2_code' => 'LR', 'name' => 'LIBERIA', 'code' => '231'],
    ['alpha_2_code' => 'LS', 'name' => 'LESOTHO', 'code' => '266'],
    ['alpha_2_code' => 'LT', 'name' => 'LITHUANIA', 'code' => '370'],
    ['alpha_2_code' => 'LU', 'name' => 'LUXEMBOURG', 'code' => '352'],
    ['alpha_2_code' => 'LV', 'name' => 'LATVIA', 'code' => '371'],
    ['alpha_2_code' => 'LY', 'name' => 'LIBYAN ARAB JAMAHIRIYA', 'code' => '218'],
    ['alpha_2_code' => 'MA', 'name' => 'MOROCCO', 'code' => '212'],
    ['alpha_2_code' => 'MC', 'name' => 'MONACO', 'code' => '377'],
    ['alpha_2_code' => 'MD', 'name' => 'MOLDOVA, REPUBLIC OF', 'code' => '373'],
    ['alpha_2_code' => 'ME', 'name' => 'MONTENEGRO', 'code' => '382'],
    ['alpha_2_code' => 'MF', 'name' => 'SAINT MARTIN', 'code' => '1599'],
    ['alpha_2_code' => 'MG', 'name' => 'MADAGASCAR', 'code' => '261'],
    ['alpha_2_code' => 'MH', 'name' => 'MARSHALL ISLANDS', 'code' => '692'],
    ['alpha_2_code' => 'MK', 'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'code' => '389'],
    ['alpha_2_code' => 'ML', 'name' => 'MALI', 'code' => '223'],
    ['alpha_2_code' => 'MM', 'name' => 'MYANMAR', 'code' => '95'],
    ['alpha_2_code' => 'MN', 'name' => 'MONGOLIA', 'code' => '976'],
    ['alpha_2_code' => 'MO', 'name' => 'MACAU', 'code' => '853'],
    ['alpha_2_code' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS', 'code' => '1670'],
    ['alpha_2_code' => 'MR', 'name' => 'MAURITANIA', 'code' => '222'],
    ['alpha_2_code' => 'MS', 'name' => 'MONTSERRAT', 'code' => '1664'],
    ['alpha_2_code' => 'MT', 'name' => 'MALTA', 'code' => '356'],
    ['alpha_2_code' => 'MU', 'name' => 'MAURITIUS', 'code' => '230'],
    ['alpha_2_code' => 'MV', 'name' => 'MALDIVES', 'code' => '960'],
    ['alpha_2_code' => 'MW', 'name' => 'MALAWI', 'code' => '265'],
    ['alpha_2_code' => 'MX', 'name' => 'MEXICO', 'code' => '52'],
    ['alpha_2_code' => 'MY', 'name' => 'MALAYSIA', 'code' => '60'],
    ['alpha_2_code' => 'MZ', 'name' => 'MOZAMBIQUE', 'code' => '258'],
    ['alpha_2_code' => 'NA', 'name' => 'NAMIBIA', 'code' => '264'],
    ['alpha_2_code' => 'NC', 'name' => 'NEW CALEDONIA', 'code' => '687'],
    ['alpha_2_code' => 'NE', 'name' => 'NIGER', 'code' => '227'],
    ['alpha_2_code' => 'NG', 'name' => 'NIGERIA', 'code' => '234'],
    ['alpha_2_code' => 'NI', 'name' => 'NICARAGUA', 'code' => '505'],
    ['alpha_2_code' => 'NL', 'name' => 'NETHERLANDS', 'code' => '31'],
    ['alpha_2_code' => 'NO', 'name' => 'NORWAY', 'code' => '47'],
    ['alpha_2_code' => 'NP', 'name' => 'NEPAL', 'code' => '977'],
    ['alpha_2_code' => 'NR', 'name' => 'NAURU', 'code' => '674'],
    ['alpha_2_code' => 'NU', 'name' => 'NIUE', 'code' => '683'],
    ['alpha_2_code' => 'NZ', 'name' => 'NEW ZEALAND', 'code' => '64'],
    ['alpha_2_code' => 'OM', 'name' => 'OMAN', 'code' => '968'],
    ['alpha_2_code' => 'PA', 'name' => 'PANAMA', 'code' => '507'],
    ['alpha_2_code' => 'PE', 'name' => 'PERU', 'code' => '51'],
    ['alpha_2_code' => 'PF', 'name' => 'FRENCH POLYNESIA', 'code' => '689'],
    ['alpha_2_code' => 'PG', 'name' => 'PAPUA NEW GUINEA', 'code' => '675'],
    ['alpha_2_code' => 'PH', 'name' => 'PHILIPPINES', 'code' => '63'],
    ['alpha_2_code' => 'PK', 'name' => 'PAKISTAN', 'code' => '92'],
    ['alpha_2_code' => 'PL', 'name' => 'POLAND', 'code' => '48'],
    ['alpha_2_code' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON', 'code' => '508'],
    ['alpha_2_code' => 'PN', 'name' => 'PITCAIRN', 'code' => '870'],
    ['alpha_2_code' => 'PR', 'name' => 'PUERTO RICO', 'code' => '1'],
    ['alpha_2_code' => 'PT', 'name' => 'PORTUGAL', 'code' => '351'],
    ['alpha_2_code' => 'PW', 'name' => 'PALAU', 'code' => '680'],
    ['alpha_2_code' => 'PY', 'name' => 'PARAGUAY', 'code' => '595'],
    ['alpha_2_code' => 'QA', 'name' => 'QATAR', 'code' => '974'],
    ['alpha_2_code' => 'RO', 'name' => 'ROMANIA', 'code' => '40'],
    ['alpha_2_code' => 'RS', 'name' => 'SERBIA', 'code' => '381'],
    ['alpha_2_code' => 'RU', 'name' => 'RUSSIAN FEDERATION', 'code' => '7'],
    ['alpha_2_code' => 'RW', 'name' => 'RWANDA', 'code' => '250'],
    ['alpha_2_code' => 'SA', 'name' => 'SAUDI ARABIA', 'code' => '966'],
    ['alpha_2_code' => 'SB', 'name' => 'SOLOMON ISLANDS', 'code' => '677'],
    ['alpha_2_code' => 'SC', 'name' => 'SEYCHELLES', 'code' => '248'],
    ['alpha_2_code' => 'SD', 'name' => 'SUDAN', 'code' => '249'],
    ['alpha_2_code' => 'SE', 'name' => 'SWEDEN', 'code' => '46'],
    ['alpha_2_code' => 'SG', 'name' => 'SINGAPORE', 'code' => '65'],
    ['alpha_2_code' => 'SH', 'name' => 'SAINT HELENA', 'code' => '290'],
    ['alpha_2_code' => 'SI', 'name' => 'SLOVENIA', 'code' => '386'],
    ['alpha_2_code' => 'SK', 'name' => 'SLOVAKIA', 'code' => '421'],
    ['alpha_2_code' => 'SL', 'name' => 'SIERRA LEONE', 'code' => '232'],
    ['alpha_2_code' => 'SM', 'name' => 'SAN MARINO', 'code' => '378'],
    ['alpha_2_code' => 'SN', 'name' => 'SENEGAL', 'code' => '221'],
    ['alpha_2_code' => 'SO', 'name' => 'SOMALIA', 'code' => '252'],
    ['alpha_2_code' => 'SR', 'name' => 'SURINAME', 'code' => '597'],
    ['alpha_2_code' => 'ST', 'name' => 'SAO TOME AND PRINCIPE', 'code' => '239'],
    ['alpha_2_code' => 'SV', 'name' => 'EL SALVADOR', 'code' => '503'],
    ['alpha_2_code' => 'SY', 'name' => 'SYRIAN ARAB REPUBLIC', 'code' => '963'],
    ['alpha_2_code' => 'SZ', 'name' => 'SWAZILAND', 'code' => '268'],
    ['alpha_2_code' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS', 'code' => '1649'],
    ['alpha_2_code' => 'TD', 'name' => 'CHAD', 'code' => '235'],
    ['alpha_2_code' => 'TG', 'name' => 'TOGO', 'code' => '228'],
    ['alpha_2_code' => 'TH', 'name' => 'THAILAND', 'code' => '66'],
    ['alpha_2_code' => 'TJ', 'name' => 'TAJIKISTAN', 'code' => '992'],
    ['alpha_2_code' => 'TK', 'name' => 'TOKELAU', 'code' => '690'],
    ['alpha_2_code' => 'TL', 'name' => 'TIMOR-LESTE', 'code' => '670'],
    ['alpha_2_code' => 'TM', 'name' => 'TURKMENISTAN', 'code' => '993'],
    ['alpha_2_code' => 'TN', 'name' => 'TUNISIA', 'code' => '216'],
    ['alpha_2_code' => 'TO', 'name' => 'TONGA', 'code' => '676'],
    ['alpha_2_code' => 'TR', 'name' => 'TURKEY', 'code' => '90'],
    ['alpha_2_code' => 'TT', 'name' => 'TRINIDAD AND TOBAGO', 'code' => '1868'],
    ['alpha_2_code' => 'TV', 'name' => 'TUVALU', 'code' => '688'],
    ['alpha_2_code' => 'TW', 'name' => 'TAIWAN, PROVINCE OF CHINA', 'code' => '886'],
    ['alpha_2_code' => 'TZ', 'name' => 'TANZANIA, UNITED REPUBLIC OF', 'code' => '255'],
    ['alpha_2_code' => 'UA', 'name' => 'UKRAINE', 'code' => '380'],
    ['alpha_2_code' => 'UG', 'name' => 'UGANDA', 'code' => '256'],
    ['alpha_2_code' => 'US', 'name' => 'UNITED STATES', 'code' => '1'],
    ['alpha_2_code' => 'UY', 'name' => 'URUGUAY', 'code' => '598'],
    ['alpha_2_code' => 'UZ', 'name' => 'UZBEKISTAN', 'code' => '998'],
    ['alpha_2_code' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)', 'code' => '39'],
    ['alpha_2_code' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES', 'code' => '1784'],
    ['alpha_2_code' => 'VE', 'name' => 'VENEZUELA', 'code' => '58'],
    ['alpha_2_code' => 'VG', 'name' => 'VIRGIN ISLANDS, BRITISH', 'code' => '1284'],
    ['alpha_2_code' => 'VI', 'name' => 'VIRGIN ISLANDS, U.S.', 'code' => '1340'],
    ['alpha_2_code' => 'VN', 'name' => 'VIET NAM', 'code' => '84'],
    ['alpha_2_code' => 'VU', 'name' => 'VANUATU', 'code' => '678'],
    ['alpha_2_code' => 'WF', 'name' => 'WALLIS AND FUTUNA', 'code' => '681'],
    ['alpha_2_code' => 'WS', 'name' => 'SAMOA', 'code' => '685'],
    ['alpha_2_code' => 'XK', 'name' => 'KOSOVO', 'code' => '381'],
    ['alpha_2_code' => 'YE', 'name' => 'YEMEN', 'code' => '967'],
    ['alpha_2_code' => 'YT', 'name' => 'MAYOTTE', 'code' => '262'],
    ['alpha_2_code' => 'ZA', 'name' => 'SOUTH AFRICA', 'code' => '27'],
    ['alpha_2_code' => 'ZM', 'name' => 'ZAMBIA', 'code' => '260'],
    ['alpha_2_code' => 'ZW', 'name' => 'ZIMBABWE', 'code' => '263']
];
